# Generated by Django 2.2.19 on 2022-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribemodel',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddConstraint(
            model_name='subscribemodel',
            constraint=models.UniqueConstraint(fields=('author', 'follower'), name='unique_subsscribe'),
        ),
    ]
